# Generated by Django 5.1 on 2024-11-21 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cargo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notification',
            options={'ordering': ['-created_timestamp']},
        ),
    ]
